# Generated by Django 5.1.2 on 2024-12-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='calificacion',
            field=models.IntegerField(choices=[(1, '⭐ 1 estrella'), (2, '⭐⭐ 2 estrellas'), (3, '⭐⭐⭐ 3 estrellas'), (4, '⭐⭐⭐⭐ 4 estrellas'), (5, '⭐⭐⭐⭐⭐ 5 estrellas')], help_text='Selecciona una calificación entre 1 (peor) y 5 (mejor)'),
        ),
    ]
