# Generated by Django 5.1.2 on 2024-11-20 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propiedad',
            old_name='propietario',
            new_name='propietario_id',
        ),
    ]
