# Generated by Django 5.1.2 on 2024-11-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='imagen_url',
            field=models.ImageField(blank=True, null=True, upload_to='propiedades/'),
        ),
    ]
