# Generated by Django 5.1.2 on 2024-12-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_feedback_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='huespedes',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha_firma',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='favorito',
            name='fecha_agregado',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='historialactividad',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha_completado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha_solicitud',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='fecha_inscripcion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_reserva',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reseña',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='valoracion',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='verificacionidentidad',
            name='fecha_verificacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
