# Generated by Django 5.1.2 on 2024-11-20 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_propietario_propiedad_propietario_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propiedad',
            old_name='propietario_id',
            new_name='propietario',
        ),
    ]
