# Generated by Django 5.1.2 on 2024-11-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_propiedad_imagen_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='imagen_url',
        ),
        migrations.AddField(
            model_name='propiedad',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
