# Generated by Django 5.1.2 on 2024-11-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_propiedad_imagen_url_propiedad_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='fecha_publicacion',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='imagen',
        ),
        migrations.AddField(
            model_name='propiedad',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
