# Generated by Django 5.1.2 on 2024-11-21 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_inquilino_reserva_cliente_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valoracion',
            old_name='propiedad',
            new_name='propiedad_id',
        ),
        migrations.RenameField(
            model_name='valoracion',
            old_name='usuario',
            new_name='usuario_id',
        ),
    ]
