# Generated by Django 5.1.2 on 2024-11-27 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_propiedad_fecha_publicacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propiedad',
            old_name='propietario_id',
            new_name='propietario_id_id',
        ),
    ]
