# Generated by Django 5.1.2 on 2024-11-27 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_propietario_id_propiedad_propietario_id_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propiedad',
            old_name='imagen_url',
            new_name='imagen',
        ),
    ]
