# Generated by Django 5.1.2 on 2024-11-21 21:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_usuario_notificacion_usuario_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallepropiedad',
            old_name='imagenes',
            new_name='imagenes_id',
        ),
        migrations.RenameField(
            model_name='detallepropiedad',
            old_name='propiedad',
            new_name='propiedad_id',
        ),
        migrations.RenameField(
            model_name='detallepropiedad',
            old_name='servicios',
            new_name='servicios_id',
        ),
        migrations.RenameField(
            model_name='favorito',
            old_name='propiedad',
            new_name='propiedad_id',
        ),
        migrations.RenameField(
            model_name='favorito',
            old_name='usuario',
            new_name='usuario_id',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='usuario',
            new_name='usuario_id',
        ),
        migrations.RenameField(
            model_name='historialactividad',
            old_name='usuario',
            new_name='usuario_id',
        ),
        migrations.RenameField(
            model_name='imagenpropiedad',
            old_name='propiedad',
            new_name='propiedad_id',
        ),
        migrations.RenameField(
            model_name='mantenimiento',
            old_name='propiedad',
            new_name='propiedad_id',
        ),
        migrations.RenameField(
            model_name='propiedadservicio',
            old_name='propiedad',
            new_name='propiedad_id',
        ),
        migrations.RenameField(
            model_name='propiedadservicio',
            old_name='servicio',
            new_name='servicio_id',
        ),
        migrations.RenameField(
            model_name='reseña',
            old_name='propiedad',
            new_name='propiedad_id',
        ),
        migrations.RenameField(
            model_name='reseña',
            old_name='usuario',
            new_name='usuario_id',
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='propiedad',
            new_name='propiedad_id',
        ),
        migrations.RenameField(
            model_name='ubicacion',
            old_name='propiedad',
            new_name='propiedad_id',
        ),
        migrations.RenameField(
            model_name='verificacionidentidad',
            old_name='usuario',
            new_name='usuario_id',
        ),
        migrations.AlterUniqueTogether(
            name='favorito',
            unique_together={('usuario_id', 'propiedad_id')},
        ),
        migrations.AlterUniqueTogether(
            name='propiedadservicio',
            unique_together={('propiedad_id', 'servicio_id')},
        ),
        migrations.AlterUniqueTogether(
            name='reseña',
            unique_together={('usuario_id', 'propiedad_id')},
        ),
    ]
