# Generated by Django 5.1.2 on 2024-11-22 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_imagenes_detallepropiedad_imagenes_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallepropiedad',
            old_name='valoraciones',
            new_name='valoraciones_id',
        ),
    ]
