# Generated by Django 5.1.2 on 2024-11-22 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_valoraciones_detallepropiedad_valoraciones_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetallePropiedad',
        ),
    ]
