# Generated by Django 5.1.2 on 2024-11-28 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_imagen_url_propiedad_imagen'),
        ('api', '0011_delete_detallepropiedad'),
    ]

    operations = [
    ]
